spring:
  application:
    name: boogakcong
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
        hbm2ddl:
          jdbc_metadata_extraction_strategy: individually
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123456
    driver-class-name:

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret: { jwt-secret-key }

kakao:
  map:
    api:
      key: { kakao-map-api-key }


aws:
  region: ap-northeast-2  # AWS S3가 위치한 리전
  accessKeyId: { aws-access-key-id }
  secretKey: { aws-secret-key }
  s3:
    bucket: { aws-s3-bucket }
